server:
  port: 8080
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: school
          uri: lb://SCHOOL-SERVICE
          predicates:
            - Path=/school/** 
        - id: student
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/student/** 

  