server:
  port: 8080
spring:
  application:
    name: GATEWAY-SERVICE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: school
          uri: lb://SCHOOL-SERVICE
          predicates:
            - Path=/school/** 
        - id: student
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/student/** 

  